import type { Env } from "./types";

export function accountPortal(env: Env, requestId: string): Response {
  const version = env.DEPLOYMENT_VERSION ?? "2.0.17";
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PosApp Cloud Account</title><meta name="posapp-portal-version" content="${version}">
<style>
:root{font-family:Inter,system-ui,"Segoe UI",sans-serif;color-scheme:light dark}*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#edf3ff;min-height:100vh}main{width:min(980px,calc(100% - 28px));margin:auto;padding:28px 0}.card{background:#121d2f;border:1px solid #2a3a53;border-radius:18px;padding:22px;margin-bottom:16px}h1,h2{margin-top:0}.muted{color:#aebbd0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}label{display:grid;gap:6px;font-weight:650}input{width:100%;padding:12px;border:1px solid #44556f;border-radius:10px;background:#0e1726;color:inherit}button,a.button{border:0;border-radius:10px;padding:11px 15px;background:#3478f6;color:white;font:inherit;font-weight:700;cursor:pointer;text-decoration:none}button.danger{background:#b8324b}button.secondary,a.secondary{background:#2a3a53}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.tabs{display:flex;gap:8px;margin-bottom:16px}.tabs button.active{outline:2px solid #9cc0ff}.hidden{display:none!important}.message{padding:11px 13px;border-radius:10px;margin-top:13px;background:#24344d}.message.error{background:#491f2b;color:#ffd2da}.message.ok{background:#153f2d;color:#b8f5cf}.summary{display:flex;gap:14px;flex-wrap:wrap}.metric{padding:14px 18px;border-radius:12px;background:#0e1726}.metric strong{font-size:1.5rem;display:block}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{text-align:left;padding:11px;border-bottom:1px solid #2a3a53}small{color:#aebbd0}@media(max-width:680px){.grid{grid-template-columns:1fr}table,thead,tbody,tr,th,td{display:block}thead{display:none}tr{padding:12px 0;border-bottom:1px solid #2a3a53}td{border:0;padding:4px 0}}
@media(prefers-color-scheme:light){body{background:#eef3f9;color:#122033}.card{background:#fff;border-color:#d1dbe8}.muted,small{color:#58697e}input,.metric{background:#f7f9fc;color:#122033;border-color:#bdc9d8}th,td,tr{border-color:#d9e1eb}}
</style></head><body><main>
<section class="card"><h1>PosApp Cloud Account</h1><p class="muted">Sign in to manage your organization users. Administrators can view user totals and remove accounts safely.</p><div class="actions"><a class="button secondary" href="/status">Cloud status</a><a class="button secondary" href="/api/v1/meta">API metadata</a></div></section>
<section id="authCard" class="card"><div class="tabs"><button id="loginTab" class="active">Sign in</button><button id="signupTab" class="secondary">Create organization</button></div>
<form id="loginForm"><div class="grid"><label>Username or email<input id="loginId" autocomplete="username" required></label><label>Online password<input id="loginPassword" type="password" autocomplete="current-password" required></label></div><div class="actions"><button type="submit">Sign in</button></div></form>
<form id="signupForm" class="hidden"><div class="grid"><label>Organization name<input id="orgName" required maxlength="160"></label><label>Store name<input id="storeName" required maxlength="160"></label><label>Full name<input id="fullName" required maxlength="100"></label><label>Username<input id="username" required maxlength="60"></label><label>Email<input id="email" type="email" required maxlength="255"></label><label>Password<input id="signupPassword" type="password" required minlength="10" maxlength="128"></label></div><small>Password must be 10–128 characters and contain at least one letter and one number.</small><div class="actions"><button type="submit">Create organization</button></div></form><div id="authMessage"></div></section>
<section id="dashboard" class="card hidden"><div class="actions" style="justify-content:space-between"><div><h2 id="organizationName">Organization</h2><p id="signedInAs" class="muted"></p></div><button id="logout" class="secondary">Sign out</button></div><div class="summary"><div class="metric"><strong id="totalUsers">0</strong>Total users</div><div class="metric"><strong id="activeUsers">0</strong>Active users</div></div><div id="dashboardMessage"></div><table><thead><tr><th>Name</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody id="users"></tbody></table></section>
</main><script nonce="${crypto.randomUUID().replaceAll("-","")}">
const schemaVersion=4; const authCard=document.getElementById('authCard'),dashboard=document.getElementById('dashboard');
const authMessage=document.getElementById('authMessage'),dashboardMessage=document.getElementById('dashboardMessage');
const deviceId=localStorage.posappPortalDeviceId||(localStorage.posappPortalDeviceId=crypto.randomUUID());
const device={id:deviceId,name:'Web account portal',operatingSystem:navigator.platform||'Web',machineName:'Browser'};
let accessToken=sessionStorage.posappAccessToken||''; let currentUserId='';
function msg(node,text,type='error'){node.innerHTML=text?'<div class="message '+type+'"></div>':'';if(text)node.firstElementChild.textContent=text}
async function api(path,options={}){const headers={'content-type':'application/json','accept':'application/json',...(options.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;const response=await fetch(path,{...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error((body.error&&body.error.message)||body.message||('Request failed with HTTP '+response.status)+(body.requestId?' · Request ID: '+body.requestId:''));return body}
function showTab(signup){document.getElementById('loginForm').classList.toggle('hidden',signup);document.getElementById('signupForm').classList.toggle('hidden',!signup);document.getElementById('loginTab').classList.toggle('active',!signup);document.getElementById('signupTab').classList.toggle('active',signup);msg(authMessage,'')}
document.getElementById('loginTab').onclick=()=>showTab(false);document.getElementById('signupTab').onclick=()=>showTab(true);
async function completeAuth(body){accessToken=body.tokens.accessToken;sessionStorage.posappAccessToken=accessToken;currentUserId=body.user.id;document.getElementById('organizationName').textContent=body.organizationName||'Organization';document.getElementById('signedInAs').textContent='Signed in as '+body.user.fullName+' ('+body.user.username+')';authCard.classList.add('hidden');dashboard.classList.remove('hidden');await loadUsers()}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();msg(authMessage,'Signing in…','ok');try{const body=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({usernameOrEmail:loginId.value.trim(),password:loginPassword.value,device,clientSchemaVersion:schemaVersion})});await completeAuth(body)}catch(error){msg(authMessage,error.message)}};
document.getElementById('signupForm').onsubmit=async e=>{e.preventDefault();msg(authMessage,'Creating organization…','ok');try{const body=await api('/api/v1/auth/signup',{method:'POST',body:JSON.stringify({organizationName:orgName.value.trim(),storeName:storeName.value.trim(),fullName:fullName.value.trim(),username:username.value.trim(),email:email.value.trim(),password:signupPassword.value,device,clientSchemaVersion:schemaVersion})});await completeAuth(body)}catch(error){msg(authMessage,error.message)}};
async function loadUsers(){msg(dashboardMessage,'Loading users…','ok');try{const body=await api('/api/v1/users');const users=body.users||[];document.getElementById('totalUsers').textContent=users.length;document.getElementById('activeUsers').textContent=users.filter(x=>x.isActive).length;const tbody=document.getElementById('users');tbody.replaceChildren();for(const user of users){const tr=document.createElement('tr');for(const value of [user.fullName,user.username,user.email,user.roleName,user.isActive?'Active':'Removed']){const td=document.createElement('td');td.textContent=value;tr.appendChild(td)}const action=document.createElement('td');if(user.id!==currentUserId&&user.isActive){const button=document.createElement('button');button.className='danger';button.textContent='Delete';button.onclick=async()=>{if(!confirm('Delete '+user.fullName+'? This revokes all sessions and removes access.'))return;button.disabled=true;try{await api('/api/v1/users/'+user.id,{method:'DELETE'});await loadUsers()}catch(error){msg(dashboardMessage,error.message);button.disabled=false}};action.appendChild(button)}else action.textContent=user.id===currentUserId?'Current account':'—';tr.appendChild(action);tbody.appendChild(tr)}msg(dashboardMessage,'','ok')}catch(error){msg(dashboardMessage,error.message)}}
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('posappAccessToken');accessToken='';dashboard.classList.add('hidden');authCard.classList.remove('hidden');msg(authMessage,'Signed out.','ok')};
if(accessToken){api('/api/v1/account/profile').then(p=>{currentUserId=p.user.id;document.getElementById('organizationName').textContent=p.organizationName;document.getElementById('signedInAs').textContent='Signed in as '+p.user.fullName+' ('+p.user.username+')';authCard.classList.add('hidden');dashboard.classList.remove('hidden');loadUsers()}).catch(()=>{sessionStorage.removeItem('posappAccessToken');accessToken=''})}
</script></body></html>`;
  return new Response(html,{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer","content-security-policy":"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'","x-posapp-portal":"1","x-posapp-deployment-version":version,"x-request-id":requestId}});
}
