import type { Env } from "./types";

export function accountPortal(env: Env, requestId: string): Response {
  const version = escapeHtml(env.DEPLOYMENT_VERSION ?? "2.1.1");
  const nonce = crypto.randomUUID().replaceAll("-", "");
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PosApp Cloud Account</title><meta name="posapp-portal-version" content="${version}">
<style>
:root{font-family:Inter,system-ui,"Segoe UI",sans-serif;color-scheme:light dark}*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#edf3ff;min-height:100vh}main{width:min(980px,calc(100% - 28px));margin:auto;padding:28px 0}.card{background:#121d2f;border:1px solid #2a3a53;border-radius:18px;padding:22px;margin-bottom:16px}h1,h2{margin-top:0}.muted{color:#aebbd0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}label{display:grid;gap:6px;font-weight:650}input{width:100%;padding:12px;border:1px solid #44556f;border-radius:10px;background:#0e1726;color:inherit}button,a.button{border:0;border-radius:10px;padding:11px 15px;background:#3478f6;color:white;font:inherit;font-weight:700;cursor:pointer;text-decoration:none}button:disabled{cursor:wait;opacity:.65}button.danger{background:#b8324b}button.secondary,a.secondary{background:#2a3a53}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.tabs{display:flex;gap:8px;margin-bottom:16px}.tabs button.active{outline:2px solid #9cc0ff}.hidden{display:none!important}.message{padding:11px 13px;border-radius:10px;margin-top:13px;background:#24344d}.message.error{background:#491f2b;color:#ffd2da}.message.ok{background:#153f2d;color:#b8f5cf}.summary{display:flex;gap:14px;flex-wrap:wrap}.metric{padding:14px 18px;border-radius:12px;background:#0e1726}.metric strong{font-size:1.5rem;display:block}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{text-align:left;padding:11px;border-bottom:1px solid #2a3a53}small{color:#aebbd0}@media(max-width:680px){.grid{grid-template-columns:1fr}table,thead,tbody,tr,th,td{display:block}thead{display:none}tr{padding:12px 0;border-bottom:1px solid #2a3a53}td{border:0;padding:4px 0}}
@media(prefers-color-scheme:light){body{background:#eef3f9;color:#122033}.card{background:#fff;border-color:#d1dbe8}.muted,small{color:#58697e}input,.metric{background:#f7f9fc;color:#122033;border-color:#bdc9d8}th,td,tr{border-color:#d9e1eb}}
</style></head><body><main>
<section class="card"><h1>PosApp Cloud Account</h1><p class="muted">Sign in with an organization administrator's online PosApp username or email and password. Administrators can view exact user totals and remove accounts safely within their own organization.</p><div class="actions"><a class="button secondary" href="/status">Cloud status</a><a class="button secondary" href="/api/v1/meta">API metadata</a></div></section>
<section id="authCard" class="card"><div class="tabs"><button id="loginTab" class="active" type="button">Sign in</button><button id="signupTab" class="secondary" type="button">Create organization</button></div>
<form id="loginForm"><div class="grid"><label>Username or email<input id="loginId" autocomplete="username" required maxlength="255"></label><label>Online password<input id="loginPassword" type="password" autocomplete="current-password" required maxlength="128"></label></div><small>Use the password created in PosApp. A Cloudflare API token or GitHub Actions secret is not a user password.</small><div class="actions"><button type="submit">Sign in</button></div></form>
<form id="signupForm" class="hidden"><div class="grid"><label>Organization name<input id="orgName" required maxlength="160"></label><label>Store name<input id="storeName" required maxlength="160"></label><label>Full name<input id="fullName" required maxlength="100"></label><label>Username<input id="username" required maxlength="60"></label><label>Email<input id="email" type="email" required maxlength="255"></label><label>Password<input id="signupPassword" type="password" required minlength="10" maxlength="128" autocomplete="new-password"></label></div><small>Password must be 10–128 characters and contain at least one letter and one number.</small><div class="actions"><button type="submit">Create organization</button></div></form><div id="authMessage"></div></section>
<section id="dashboard" class="card hidden"><div class="actions" style="justify-content:space-between"><div><h2 id="organizationName">Organization</h2><p id="signedInAs" class="muted"></p></div><div class="actions"><button id="createAnother" class="secondary" type="button">Create another organization</button><button id="logout" class="secondary" type="button">Sign out</button></div></div><div class="summary"><div class="metric"><strong id="totalUsers">0</strong>Total users</div><div class="metric"><strong id="activeUsers">0</strong>Active users</div></div><div id="dashboardMessage"></div><table><thead><tr><th>Name</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody id="users"></tbody></table><small id="usersNote"></small></section>
</main><script nonce="${nonce}">
const schemaVersion=4,authCard=document.getElementById('authCard'),dashboard=document.getElementById('dashboard'),authMessage=document.getElementById('authMessage'),dashboardMessage=document.getElementById('dashboardMessage');
let deviceId=sessionStorage.posappPortalDeviceId||localStorage.posappPortalDeviceId||crypto.randomUUID();
function deviceFor(id){return {id,name:'Web account portal',operatingSystem:navigator.platform||'Web',machineName:'Browser'}}
function selectDevice(id){deviceId=id;sessionStorage.posappPortalDeviceId=id;localStorage.posappPortalDeviceId=id}
function readDeviceProfiles(){try{return JSON.parse(localStorage.posappPortalDeviceProfiles||'{}')}catch{return {}}}
function preferredDevice(identifier){const saved=readDeviceProfiles()[identifier.trim().toLowerCase()];return saved&&saved.deviceId?saved.deviceId:deviceId}
function rememberDevice(body,id,identifiers){const saved=readDeviceProfiles(),record={deviceId:id,organizationId:body.organizationId||'',organizationName:body.organizationName||'',lastUsedAt:new Date().toISOString()};for(const value of identifiers.filter(Boolean))saved[String(value).trim().toLowerCase()]=record;localStorage.posappPortalDeviceProfiles=JSON.stringify(saved);selectDevice(id)}
let accessToken=sessionStorage.posappAccessToken||'',refreshToken=sessionStorage.posappRefreshToken||'',sessionId=sessionStorage.posappSessionId||'',currentUserId='',refreshPromise=null;
function msg(node,value,type='error'){node.replaceChildren();if(!value)return;const item=document.createElement('div');item.className='message '+type;item.textContent=value;node.appendChild(item)}
function saveTokens(tokens){accessToken=tokens.accessToken||'';refreshToken=tokens.refreshToken||'';sessionId=tokens.sessionId||sessionId;sessionStorage.posappAccessToken=accessToken;sessionStorage.posappRefreshToken=refreshToken;sessionStorage.posappSessionId=sessionId}
function clearTokens(){accessToken='';refreshToken='';sessionId='';sessionStorage.removeItem('posappAccessToken');sessionStorage.removeItem('posappRefreshToken');sessionStorage.removeItem('posappSessionId')}
async function parse(response){try{return await response.json()}catch{return {}}}
async function renew(){if(!refreshToken||!sessionId)return false;try{const response=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({refreshToken,sessionId,deviceId})});const body=await parse(response);if(!response.ok||!body.tokens){clearTokens();return false}saveTokens(body.tokens);return true}catch{clearTokens();return false}}
async function renewOnce(){if(!refreshPromise)refreshPromise=renew().finally(()=>{refreshPromise=null});return await refreshPromise}
async function api(path,options={},retry=true){const headers={'content-type':'application/json','accept':'application/json',...(options.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;let response=await fetch(path,{...options,headers});if(response.status===401&&retry&&refreshToken&&path!='/api/v1/auth/refresh'&&await renewOnce()){headers.authorization='Bearer '+accessToken;response=await fetch(path,{...options,headers})}const body=await parse(response);if(!response.ok){const base=(body.error&&body.error.message)||body.message||('Request failed with HTTP '+response.status),error=new Error(base+(body.requestId?' · Request ID: '+body.requestId:''));error.code=body.error&&body.error.code;throw error}return body}
function showTab(signup){document.getElementById('loginForm').classList.toggle('hidden',signup);document.getElementById('signupForm').classList.toggle('hidden',!signup);document.getElementById('loginTab').classList.toggle('active',!signup);document.getElementById('signupTab').classList.toggle('active',signup);msg(authMessage,'')}
document.getElementById('loginTab').onclick=()=>showTab(false);document.getElementById('signupTab').onclick=()=>showTab(true);
function showAccount(user,organizationName){currentUserId=user.id;document.getElementById('organizationName').textContent=organizationName||'Organization';document.getElementById('signedInAs').textContent='Signed in as '+user.fullName+' ('+user.username+')';authCard.classList.add('hidden');dashboard.classList.remove('hidden')}
async function completeAuth(body,usedDeviceId,identifiers){saveTokens(body.tokens);rememberDevice(body,usedDeviceId,[...identifiers,body.user&&body.user.username,body.user&&body.user.email]);showAccount(body.user,body.organizationName);await loadUsers()}
async function loginRequest(identifier,password,candidateId){return await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({usernameOrEmail:identifier,password,device:deviceFor(candidateId),clientSchemaVersion:schemaVersion})})}
document.getElementById('loginForm').onsubmit=async event=>{event.preventDefault();msg(authMessage,'Signing in…','ok');const identifier=document.getElementById('loginId').value.trim(),password=document.getElementById('loginPassword').value;let candidateId=preferredDevice(identifier);try{let body;try{body=await loginRequest(identifier,password,candidateId)}catch(error){if(error.code!=='DEVICE_TENANT_MISMATCH')throw error;candidateId=crypto.randomUUID();body=await loginRequest(identifier,password,candidateId)}document.getElementById('loginPassword').value='';await completeAuth(body,candidateId,[identifier])}catch(error){msg(authMessage,error.message)}};
document.getElementById('signupForm').onsubmit=async event=>{event.preventDefault();msg(authMessage,'Creating organization…','ok');const candidateId=crypto.randomUUID(),username=document.getElementById('username').value.trim(),email=document.getElementById('email').value.trim();try{const body=await api('/api/v1/auth/signup',{method:'POST',body:JSON.stringify({organizationName:document.getElementById('orgName').value.trim(),storeName:document.getElementById('storeName').value.trim(),fullName:document.getElementById('fullName').value.trim(),username,email,password:document.getElementById('signupPassword').value,device:deviceFor(candidateId),clientSchemaVersion:schemaVersion})});document.getElementById('signupPassword').value='';await completeAuth(body,candidateId,[username,email])}catch(error){msg(authMessage,error.message)}};
async function loadUsers(){msg(dashboardMessage,'Loading users…','ok');try{const body=await api('/api/v1/users');const users=body.users||[],total=Number.isInteger(body.totalUsers)?body.totalUsers:users.length,active=Number.isInteger(body.activeUsers)?body.activeUsers:users.filter(value=>value.isActive).length;document.getElementById('totalUsers').textContent=String(total);document.getElementById('activeUsers').textContent=String(active);document.getElementById('usersNote').textContent=total>users.length?'Showing the first '+users.length+' of '+total+' users.':'';const tbody=document.getElementById('users');tbody.replaceChildren();for(const user of users){const tr=document.createElement('tr');for(const value of [user.fullName,user.username,user.email,user.roleName,user.isActive?'Active':'Removed']){const td=document.createElement('td');td.textContent=value;tr.appendChild(td)}const action=document.createElement('td');if(user.id!==currentUserId&&user.isActive){const button=document.createElement('button');button.className='danger';button.type='button';button.textContent='Delete';button.onclick=async()=>{if(!confirm('Delete '+user.fullName+'? This revokes every session and removes access. Financial history remains intact.'))return;button.disabled=true;try{await api('/api/v1/users/'+encodeURIComponent(user.id),{method:'DELETE'});await loadUsers()}catch(error){msg(dashboardMessage,error.message);button.disabled=false}};action.appendChild(button)}else action.textContent=user.id===currentUserId?'Current account':'—';tr.appendChild(action);tbody.appendChild(tr)}msg(dashboardMessage,'','ok')}catch(error){msg(dashboardMessage,error.message)}}
document.getElementById('logout').onclick=async event=>{const button=event.currentTarget;button.disabled=true;try{if(accessToken)await api('/api/v1/auth/logout',{method:'POST',body:'{}'})}catch{}finally{clearTokens();currentUserId='';dashboard.classList.add('hidden');authCard.classList.remove('hidden');button.disabled=false;msg(authMessage,'Signed out securely.','ok')}};
document.getElementById('createAnother').onclick=async event=>{const button=event.currentTarget;button.disabled=true;try{if(accessToken)await api('/api/v1/auth/logout',{method:'POST',body:'{}'})}catch{}finally{clearTokens();currentUserId='';dashboard.classList.add('hidden');authCard.classList.remove('hidden');showTab(true);button.disabled=false;msg(authMessage,'Enter the new organization details. A separate browser device identity will be created.','ok')}};
async function restore(){if(!accessToken&&refreshToken)await renewOnce();if(!accessToken)return;try{const profile=await api('/api/v1/account/profile');showAccount(profile.user,profile.organizationName);await loadUsers()}catch{clearTokens();dashboard.classList.add('hidden');authCard.classList.remove('hidden')}}restore();
</script></body></html>`;
  return new Response(html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff",
      "referrer-policy": "no-referrer",
      "permissions-policy": "camera=(), microphone=(), geolocation=()",
      "content-security-policy": `default-src 'self'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'; connect-src 'self'; img-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'`,
      "x-posapp-portal": "1",
      "x-posapp-deployment-version": version,
      "x-request-id": requestId,
    },
  });
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}
